export const reports = {
  OCEAN_DEBRIS: [
    {
      id: 1,
      lat: 13.1143,
      lng: 80.32,
      intensity: 1.0,
      type: "OCEAN_DEBRIS",
      description: "Thick oil sludge reported near Ennore Creek after cyclone Michaung.",
      date: "2023-12-04",
    },
    {
      id: 2,
      lat: 13.0827,
      lng: 80.2707,
      intensity: 0.8,
      type: "OCEAN_DEBRIS",
      description: "Oil patches and tar balls washing ashore at Marina Beach.",
      date: "2023-12-05",
    },
    {
      id: 3,
      lat: 19.0878,
      lng: 72.8256,
      intensity: 0.7,
      type: "OCEAN_DEBRIS",
      description: "Massive accumulation of plastic waste on Juhu Beach, Mumbai.",
      date: "2024-06-15",
    },
    {
      id: 4,
      lat: 8.7383,
      lng: 76.7028,
      intensity: 0.9,
      type: "OCEAN_DEBRIS",
      description: "Debris from cliff erosion at Varkala Beach, Kerala.",
      date: "2024-07-20",
    },
    {
      id: 5,
      lat: 15.2993,
      lng: 74.124,
      intensity: 0.6,
      type: "OCEAN_DEBRIS",
      description: "Microplastics and bottles reported on Goa's beaches.",
      date: "2024-05-22",
    },
    {
      id: 6,
      lat: 12.9716,
      lng: 77.5946,
      intensity: 0.5,
      type: "OCEAN_DEBRIS",
      description: "Industrial runoff causing discoloration near Mangalore port.",
      date: "2024-08-01",
    },
    {
      id: 7,
      lat: 22.5726,
      lng: 88.3639,
      intensity: 0.8,
      type: "OCEAN_DEBRIS",
      description: "Waste from Hooghly River accumulating in the Bay of Bengal.",
      date: "2024-09-10",
    },
    {
      id: 8,
      lat: 10.8505,
      lng: 76.2711,
      intensity: 0.7,
      type: "OCEAN_DEBRIS",
      description: "Abandoned fishing gear along the coast of Thrissur, Kerala.",
      date: "2024-03-18",
    },
    {
      id: 9,
      lat: 17.6868,
      lng: 83.2185,
      intensity: 0.9,
      type: "OCEAN_DEBRIS",
      description: "Shipbreaking yard waste found on RK Beach, Visakhapatnam.",
      date: "2024-02-25",
    },
    {
      id: 10,
      lat: 21.6285,
      lng: 69.6413,
      intensity: 0.8,
      type: "OCEAN_DEBRIS",
      description: "Oil residue and plastic waste near Dwarka coast, Gujarat.",
      date: "2024-01-30",
    },
  ],
  TSUNAMI_WARNING: [
    {
      id: 101,
      lat: 13.0581,
      lng: 80.2831,
      intensity: 1.0,
      type: "TSUNAMI_WARNING",
      description: "Historical Data: Reports of water receding at an unprecedented rate from Chennai Lighthouse.",
      date: "2004-12-26",
    },
    {
      id: 102,
      lat: 8.0883,
      lng: 77.5385,
      intensity: 1.0,
      type: "TSUNAMI_WARNING",
      description: "Historical Data: Catastrophic wave impact reported in Kanyakumari district.",
      date: "2004-12-26",
    },
    {
      id: 103,
      lat: 9.9189,
      lng: 76.2571,
      intensity: 0.9,
      type: "TSUNAMI_WARNING",
      description: "Historical Data: Significant flooding and wave damage reported along the Kochi coastline.",
      date: "2004-12-26",
    },
    {
      id: 104,
      lat: 6.9271,
      lng: 79.8612,
      intensity: 0.9,
      type: "TSUNAMI_WARNING",
      description: "Historical Data: Major impact on Colombo, Sri Lanka.",
      date: "2004-12-26",
    },
    {
      id: 105,
      lat: 5.5539,
      lng: 95.3221,
      intensity: 1.0,
      type: "TSUNAMI_WARNING",
      description: "Historical Data: Epicenter proximity, extreme devastation in Banda Aceh, Indonesia.",
      date: "2004-12-26",
    },
  ],
  CYCLONE_WARNING: [
    {
      id: 201,
      lat: 21.7679,
      lng: 87.7568,
      intensity: 1.0,
      type: "CYCLONE_WARNING",
      description: "Cyclone Amphan landfall reported near Sundarbans, West Bengal.",
      date: "2020-05-20",
    },
    {
      id: 202,
      lat: 22.5726,
      lng: 88.3639,
      intensity: 0.9,
      type: "CYCLONE_WARNING",
      description: "Widespread damage and flooding in Kolkata due to Amphan.",
      date: "2020-05-20",
    },
    {
      id: 203,
      lat: 19.8135,
      lng: 85.8312,
      intensity: 1.0,
      type: "CYCLONE_WARNING",
      description: "Extremely Severe Cyclone Fani made landfall in Puri, Odisha.",
      date: "2019-05-03",
    },
  ],
  FLOOD_ALERT: [
    {
      id: 301,
      lat: 13.0827,
      lng: 80.2707,
      intensity: 1.0,
      type: "FLOOD_ALERT",
      description: "Catastrophic flooding in Chennai due to record-breaking rainfall.",
      date: "2015-12-01",
    },
    {
      id: 302,
      lat: 9.9679,
      lng: 76.2999,
      intensity: 1.0,
      type: "FLOOD_ALERT",
      description: "Severe flooding across Kerala, particularly in districts like Ernakulam and Idukki.",
      date: "2018-08-15",
    },
  ],
}
